services:
  - type: web
    name: receipt-extractor-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: GOOGLE_CREDS_PATH
        value: /etc/secrets/credentials.json
      - key: TOKEN_PATH
        value: /etc/secrets/token.json
