services:
  - type: web
    name: receipt-extractor-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: GOOGLE_CREDS_PATH
        value: /etc/secrets/credentials.json
      - key: TOKEN_PATH
        value: /etc/secrets/token.json
